FROM nvidia/cuda:12.1.0-devel-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get --yes update \
 && apt-get --yes install \
    git \
    wget \
    curl \
    unzip \
    cmake \
    build-essential \
    libssl-dev \
    openjdk-17-jdk

# Setup a robotlab user as the development user, to avoid using root.
# Use the user and group ID of the builder so access is maintained.
ARG USER_UID
ARG USER_GID
ENV USER_UID=$USER_UID
ENV USER_GID=$USER_GID
RUN addgroup --gid $USER_GID robotlab \
 && adduser --uid $USER_UID --home /home/robotlab --gecos "Rosie Robot,1117,1234567,2345678" --ingroup robotlab --disabled-password robotlab \
 && chown -R robotlab /home/robotlab \
 && adduser robotlab sudo \
 && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# Install CMake
RUN wget -O /tmp/cmake.sh "https://cmake.org/files/v3.31/cmake-3.31.6-linux-x86_64.sh"
RUN mkdir -p /opt/cmake && sh /tmp/cmake.sh --prefix=/opt/cmake --exclude-subdir
RUN ln -sf /opt/cmake/bin/cmake /usr/local/bin/cmake
RUN cmake --version

WORKDIR /tmp

USER robotlab
