// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.llamacpp;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.llamacpp.global.llamacpp.*;


    @Properties(inherit = us.ihmc.llamacpp.LlamaCPPConfig.class)
public class ggml_backend_meta_split_state extends Pointer {
        static { Loader.load(); }
        /** Default native constructor. */
        public ggml_backend_meta_split_state() { super((Pointer)null); allocate(); }
        /** Native array allocator. Access with {@link Pointer#position(long)}. */
        public ggml_backend_meta_split_state(long size) { super((Pointer)null); allocateArray(size); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public ggml_backend_meta_split_state(Pointer p) { super(p); }
        private native void allocate();
        private native void allocateArray(long size);
        @Override public ggml_backend_meta_split_state position(long position) {
            return (ggml_backend_meta_split_state)super.position(position);
        }
        @Override public ggml_backend_meta_split_state getPointer(long i) {
            return new ggml_backend_meta_split_state((Pointer)this).offsetAddress(i);
        }
    
        public native ggml_backend_meta_split_axis axis(); public native ggml_backend_meta_split_state axis(ggml_backend_meta_split_axis setter);

        // for tensors with axis >= 0 && axis < GGML_MAX_DIMS:
        //   - each device has a slice of the tensor along the split axis
        //   - most tensors have n_segments == 1 and a contiguous slice of the tensor data
        //   - some tensors have an inhomogenenous data layout along the split axis,
        //     those tensors are divided into segments which are each individually split across devices
        //   - ne has one entry per segment and device and that segment repeats nr times,
        //     in total when accounting for repetitions the segments add up to ggml_tensor::ne for that axis,
        //     the outer/inner loops are over segments/devices like [seg0_dev0_r0, seg0_dev1_r0, seg0_dev0_r1, seg0_dev1_r1, seg1_dev0_r0, seg1_dev1_r0],
        //   - for example, a transformer may have a fused QKV matrix rather than 3 matrices, those would be 3 separate segments
        //     that each need to be split individually across devices so that each device gets a slice of Q, K, and V,
        //     the Q matrix can be larger than the K and V matrices so this can either be expressed as 3 segments or as 2 segments
        //     where the segment for K/V repeats twice
        public native @Cast("int64_t") long ne(int i); public native ggml_backend_meta_split_state ne(int i, long setter);
        @MemberGetter public native @Cast("int64_t*") LongPointer ne();
        public native @Cast("uint32_t") int nr(int i); public native ggml_backend_meta_split_state nr(int i, int setter);
        @MemberGetter public native @Cast("uint32_t*") IntPointer nr();
        public native @Cast("uint32_t") int n_segments(); public native ggml_backend_meta_split_state n_segments(int setter);
    }
