// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.llamacpp;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.llamacpp.global.llamacpp.*;

    @Properties(inherit = us.ihmc.llamacpp.LlamaCPPConfig.class)
public class ggml_from_float_t extends FunctionPointer {
        static { Loader.load(); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public    ggml_from_float_t(Pointer p) { super(p); }
        protected ggml_from_float_t() { allocate(); }
        private native void allocate();
        public native void call(@Const FloatPointer GGML_RESTRICT/*x*/, Pointer GGML_RESTRICT/*y*/, @Cast("int64_t") long k);
    }
