// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.llamacpp;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.llamacpp.global.llamacpp.*;

    // Set the abort callback for the backend
    @Properties(inherit = us.ihmc.llamacpp.LlamaCPPConfig.class)
public class ggml_backend_set_abort_callback_t extends FunctionPointer {
        static { Loader.load(); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public    ggml_backend_set_abort_callback_t(Pointer p) { super(p); }
        protected ggml_backend_set_abort_callback_t() { allocate(); }
        private native void allocate();
        public native void call(ggml_backend backend, @ByVal ggml_abort_callback abort_callback, Pointer abort_callback_data);
    }
