// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.llamacpp;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.llamacpp.global.llamacpp.*;


    // google brain half-precision bfloat16
    @Properties(inherit = us.ihmc.llamacpp.LlamaCPPConfig.class)
public class ggml_bf16_t extends Pointer {
        static { Loader.load(); }
        /** Default native constructor. */
        public ggml_bf16_t() { super((Pointer)null); allocate(); }
        /** Native array allocator. Access with {@link Pointer#position(long)}. */
        public ggml_bf16_t(long size) { super((Pointer)null); allocateArray(size); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public ggml_bf16_t(Pointer p) { super(p); }
        private native void allocate();
        private native void allocateArray(long size);
        @Override public ggml_bf16_t position(long position) {
            return (ggml_bf16_t)super.position(position);
        }
        @Override public ggml_bf16_t getPointer(long i) {
            return new ggml_bf16_t((Pointer)this).offsetAddress(i);
        }
     public native @Cast("uint16_t") short bits(); public native ggml_bf16_t bits(short setter); }
