// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.llamacpp;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.llamacpp.global.llamacpp.*;

// #endif

    // Function type used in fatal error callbacks
    @Properties(inherit = us.ihmc.llamacpp.LlamaCPPConfig.class)
public class ggml_abort_callback_t extends FunctionPointer {
        static { Loader.load(); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public    ggml_abort_callback_t(Pointer p) { super(p); }
        protected ggml_abort_callback_t() { allocate(); }
        private native void allocate();
        public native void call(@Cast("const char*") BytePointer error_message);
    }
