// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.llamacpp;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.llamacpp.global.llamacpp.*;

    // Get a list of feature flags supported by the backend (returns a NULL-terminated array)
    @Properties(inherit = us.ihmc.llamacpp.LlamaCPPConfig.class)
public class ggml_backend_feature extends Pointer {
        static { Loader.load(); }
        /** Default native constructor. */
        public ggml_backend_feature() { super((Pointer)null); allocate(); }
        /** Native array allocator. Access with {@link Pointer#position(long)}. */
        public ggml_backend_feature(long size) { super((Pointer)null); allocateArray(size); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public ggml_backend_feature(Pointer p) { super(p); }
        private native void allocate();
        private native void allocateArray(long size);
        @Override public ggml_backend_feature position(long position) {
            return (ggml_backend_feature)super.position(position);
        }
        @Override public ggml_backend_feature getPointer(long i) {
            return new ggml_backend_feature((Pointer)this).offsetAddress(i);
        }
    
        public native @Cast("const char*") BytePointer name(); public native ggml_backend_feature name(BytePointer setter);
        public native @Cast("const char*") BytePointer value(); public native ggml_backend_feature value(BytePointer setter);
    }
