// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.llamacpp;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.llamacpp.global.llamacpp.*;

    @Properties(inherit = us.ihmc.llamacpp.LlamaCPPConfig.class)
public class ggml_backend_comm_allreduce_tensor_t extends FunctionPointer {
        static { Loader.load(); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public    ggml_backend_comm_allreduce_tensor_t(Pointer p) { super(p); }
        protected ggml_backend_comm_allreduce_tensor_t() { allocate(); }
        private native void allocate();
        public native @Cast("bool") boolean call(Pointer comm_ctx, @Cast("ggml_tensor**") PointerPointer tensors);
    }
