// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.llamacpp;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.llamacpp.global.llamacpp.*;


    @Properties(inherit = us.ihmc.llamacpp.LlamaCPPConfig.class)
public class ggml_type_traits extends Pointer {
        static { Loader.load(); }
        /** Default native constructor. */
        public ggml_type_traits() { super((Pointer)null); allocate(); }
        /** Native array allocator. Access with {@link Pointer#position(long)}. */
        public ggml_type_traits(long size) { super((Pointer)null); allocateArray(size); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public ggml_type_traits(Pointer p) { super(p); }
        private native void allocate();
        private native void allocateArray(long size);
        @Override public ggml_type_traits position(long position) {
            return (ggml_type_traits)super.position(position);
        }
        @Override public ggml_type_traits getPointer(long i) {
            return new ggml_type_traits((Pointer)this).offsetAddress(i);
        }
    
        public native @Cast("const char*") BytePointer type_name(); public native ggml_type_traits type_name(BytePointer setter);
        public native @Cast("int64_t") long blck_size(); public native ggml_type_traits blck_size(long setter);
        public native @Cast("int64_t") long blck_size_interleave(); public native ggml_type_traits blck_size_interleave(long setter); // interleave elements in blocks
        public native @Cast("size_t") long type_size(); public native ggml_type_traits type_size(long setter);
        public native @Cast("bool") boolean is_quantized(); public native ggml_type_traits is_quantized(boolean setter);
    }
