// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.llamacpp;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.llamacpp.global.llamacpp.*;


    // TODO these functions were sandwiched in the old optimization interface, is there a better place for them?
    @Properties(inherit = us.ihmc.llamacpp.LlamaCPPConfig.class)
public class ggml_log_callback extends FunctionPointer {
        static { Loader.load(); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public    ggml_log_callback(Pointer p) { super(p); }
        protected ggml_log_callback() { allocate(); }
        private native void allocate();
        public native void call(@Cast("ggml_log_level") int level, @Cast("const char*") BytePointer text, Pointer user_data);
    }
