// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.llamacpp;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.llamacpp.global.llamacpp.*;


    @Properties(inherit = us.ihmc.llamacpp.LlamaCPPConfig.class)
public class ggml_type_traits_cpu extends Pointer {
        static { Loader.load(); }
        /** Default native constructor. */
        public ggml_type_traits_cpu() { super((Pointer)null); allocate(); }
        /** Native array allocator. Access with {@link Pointer#position(long)}. */
        public ggml_type_traits_cpu(long size) { super((Pointer)null); allocateArray(size); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public ggml_type_traits_cpu(Pointer p) { super(p); }
        private native void allocate();
        private native void allocateArray(long size);
        @Override public ggml_type_traits_cpu position(long position) {
            return (ggml_type_traits_cpu)super.position(position);
        }
        @Override public ggml_type_traits_cpu getPointer(long i) {
            return new ggml_type_traits_cpu((Pointer)this).offsetAddress(i);
        }
    
        public native ggml_type vec_dot_type(); public native ggml_type_traits_cpu vec_dot_type(ggml_type setter);
        public native @Cast("int64_t") long nrows(); public native ggml_type_traits_cpu nrows(long setter); // number of rows to process simultaneously
    }
