// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.llamacpp;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.llamacpp.global.llamacpp.*;


    // function to assign split states for statically allocated tensors, compute tensor split states will be assigned to be compatible:
    @Properties(inherit = us.ihmc.llamacpp.LlamaCPPConfig.class)
public class ggml_backend_meta_get_split_state_t extends FunctionPointer {
        static { Loader.load(); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public    ggml_backend_meta_get_split_state_t(Pointer p) { super(p); }
        protected ggml_backend_meta_get_split_state_t() { allocate(); }
        private native void allocate();
        public native @ByVal ggml_backend_meta_split_state call(@Const ggml_tensor tensor, Pointer userdata);
    }
