// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.llamacpp;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.llamacpp.global.llamacpp.*;


    @Properties(inherit = us.ihmc.llamacpp.LlamaCPPConfig.class)
public class llama_model_set_tensor_data_t extends FunctionPointer {
        static { Loader.load(); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public    llama_model_set_tensor_data_t(Pointer p) { super(p); }
        protected llama_model_set_tensor_data_t() { allocate(); }
        private native void allocate();
        public native void call(ggml_tensor tensor, Pointer userdata);
    }
