// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.llamacpp;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.llamacpp.global.llamacpp.*;


    @Properties(inherit = us.ihmc.llamacpp.LlamaCPPConfig.class)
public class llama_model_tensor_override extends Pointer {
        static { Loader.load(); }
        /** Default native constructor. */
        public llama_model_tensor_override() { super((Pointer)null); allocate(); }
        /** Native array allocator. Access with {@link Pointer#position(long)}. */
        public llama_model_tensor_override(long size) { super((Pointer)null); allocateArray(size); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public llama_model_tensor_override(Pointer p) { super(p); }
        private native void allocate();
        private native void allocateArray(long size);
        @Override public llama_model_tensor_override position(long position) {
            return (llama_model_tensor_override)super.position(position);
        }
        @Override public llama_model_tensor_override getPointer(long i) {
            return new llama_model_tensor_override((Pointer)this).offsetAddress(i);
        }
    
        public native @Cast("const char*") BytePointer pattern(); public native llama_model_tensor_override pattern(BytePointer setter);
        public native ggml_type type(); public native llama_model_tensor_override type(ggml_type setter);
    }
