// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.llamacpp;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.llamacpp.global.llamacpp.*;


    //
    // training
    //

    // function that returns whether or not a given tensor contains trainable parameters
    @Properties(inherit = us.ihmc.llamacpp.LlamaCPPConfig.class)
public class llama_opt_param_filter extends FunctionPointer {
        static { Loader.load(); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public    llama_opt_param_filter(Pointer p) { super(p); }
        protected llama_opt_param_filter() { allocate(); }
        private native void allocate();
        public native @Cast("bool") boolean call(@Const ggml_tensor tensor, Pointer userdata);
    }
