// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.llamacpp;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.llamacpp.global.llamacpp.*;


    // user code can implement the interface below in order to create custom llama_sampler
    @Properties(inherit = us.ihmc.llamacpp.LlamaCPPConfig.class)
public class llama_sampler_i extends Pointer {
        static { Loader.load(); }
        /** Default native constructor. */
        public llama_sampler_i() { super((Pointer)null); allocate(); }
        /** Native array allocator. Access with {@link Pointer#position(long)}. */
        public llama_sampler_i(long size) { super((Pointer)null); allocateArray(size); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public llama_sampler_i(Pointer p) { super(p); }
        private native void allocate();
        private native void allocateArray(long size);
        @Override public llama_sampler_i position(long position) {
            return (llama_sampler_i)super.position(position);
        }
        @Override public llama_sampler_i getPointer(long i) {
            return new llama_sampler_i((Pointer)this).offsetAddress(i);
        }
    
        public static class Name_llama_sampler extends FunctionPointer {
            static { Loader.load(); }
            /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
            public    Name_llama_sampler(Pointer p) { super(p); }
            protected Name_llama_sampler() { allocate(); }
            private native void allocate();
            public native @Cast("const char*") BytePointer call(@Const llama_sampler smpl);
        }
        public native Name_llama_sampler name(); public native llama_sampler_i name(Name_llama_sampler setter);                                 // can be NULL
        public static class Accept_llama_sampler_int extends FunctionPointer {
            static { Loader.load(); }
            /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
            public    Accept_llama_sampler_int(Pointer p) { super(p); }
            protected Accept_llama_sampler_int() { allocate(); }
            private native void allocate();
            public native void call(      llama_sampler smpl, @Cast("llama_token") int token);
        }
        public native Accept_llama_sampler_int accept(); public native llama_sampler_i accept(Accept_llama_sampler_int setter);              // can be NULL
        public static class Apply_llama_sampler_llama_token_data_array extends FunctionPointer {
            static { Loader.load(); }
            /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
            public    Apply_llama_sampler_llama_token_data_array(Pointer p) { super(p); }
            protected Apply_llama_sampler_llama_token_data_array() { allocate(); }
            private native void allocate();
            public native void call(      llama_sampler smpl, llama_token_data_array cur_p);
        }
        public native Apply_llama_sampler_llama_token_data_array apply(); public native llama_sampler_i apply(Apply_llama_sampler_llama_token_data_array setter); // required
        public static class Reset_llama_sampler extends FunctionPointer {
            static { Loader.load(); }
            /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
            public    Reset_llama_sampler(Pointer p) { super(p); }
            protected Reset_llama_sampler() { allocate(); }
            private native void allocate();
            public native void call(      llama_sampler smpl);
        }
        public native Reset_llama_sampler reset(); public native llama_sampler_i reset(Reset_llama_sampler setter);                                 // can be NULL
        public static class Clone_llama_sampler extends FunctionPointer {
            static { Loader.load(); }
            /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
            public    Clone_llama_sampler(Pointer p) { super(p); }
            protected Clone_llama_sampler() { allocate(); }
            private native void allocate();
            public native llama_sampler call(@Const llama_sampler smpl);
        }
        public native Clone_llama_sampler clone(); public native llama_sampler_i clone(Clone_llama_sampler setter);                                 // can be NULL if ctx is NULL
        public static class Free_llama_sampler extends FunctionPointer {
            static { Loader.load(); }
            /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
            public    Free_llama_sampler(Pointer p) { super(p); }
            protected Free_llama_sampler() { allocate(); }
            private native void allocate();
            public native void call(      llama_sampler smpl);
        }
        public native @Name("free") Free_llama_sampler _free(); public native llama_sampler_i _free(Free_llama_sampler setter);                                 // can be NULL if ctx is NULL

        // [EXPERIMENTAL]
        // backend sampling interface:

        // return true if the backend supports all ops needed by the sampler
        // note: call once per sampler
        public static class Backend_init_llama_sampler_ggml_backend_buffer_type extends FunctionPointer {
            static { Loader.load(); }
            /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
            public    Backend_init_llama_sampler_ggml_backend_buffer_type(Pointer p) { super(p); }
            protected Backend_init_llama_sampler_ggml_backend_buffer_type() { allocate(); }
            private native void allocate();
            public native @Cast("bool") boolean call(llama_sampler smpl, ggml_backend_buffer_type buft);
        }
        public native Backend_init_llama_sampler_ggml_backend_buffer_type backend_init(); public native llama_sampler_i backend_init(Backend_init_llama_sampler_ggml_backend_buffer_type setter);

        // call after .backend_apply()
        public static class Backend_accept_llama_sampler_ggml_context_ggml_cgraph_ggml_tensor extends FunctionPointer {
            static { Loader.load(); }
            /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
            public    Backend_accept_llama_sampler_ggml_context_ggml_cgraph_ggml_tensor(Pointer p) { super(p); }
            protected Backend_accept_llama_sampler_ggml_context_ggml_cgraph_ggml_tensor() { allocate(); }
            private native void allocate();
            public native void call(
                        llama_sampler smpl,
                        ggml_context ctx,
                        ggml_cgraph gf,
                        ggml_tensor selected_token);
        }
        public native Backend_accept_llama_sampler_ggml_context_ggml_cgraph_ggml_tensor backend_accept(); public native llama_sampler_i backend_accept(Backend_accept_llama_sampler_ggml_context_ggml_cgraph_ggml_tensor setter);

        // call after .backend_init()
        public static class Backend_apply_llama_sampler_ggml_context_ggml_cgraph_llama_sampler_data extends FunctionPointer {
            static { Loader.load(); }
            /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
            public    Backend_apply_llama_sampler_ggml_context_ggml_cgraph_llama_sampler_data(Pointer p) { super(p); }
            protected Backend_apply_llama_sampler_ggml_context_ggml_cgraph_llama_sampler_data() { allocate(); }
            private native void allocate();
            public native void call(
                        llama_sampler smpl,
                        ggml_context ctx,
                        ggml_cgraph gf,
                        llama_sampler_data data);
        }
        public native Backend_apply_llama_sampler_ggml_context_ggml_cgraph_llama_sampler_data backend_apply(); public native llama_sampler_i backend_apply(Backend_apply_llama_sampler_ggml_context_ggml_cgraph_llama_sampler_data setter);

        // called before graph execution to set inputs for the current ubatch
        public static class Backend_set_input_llama_sampler extends FunctionPointer {
            static { Loader.load(); }
            /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
            public    Backend_set_input_llama_sampler(Pointer p) { super(p); }
            protected Backend_set_input_llama_sampler() { allocate(); }
            private native void allocate();
            public native void call(llama_sampler smpl);
        }
        public native Backend_set_input_llama_sampler backend_set_input(); public native llama_sampler_i backend_set_input(Backend_set_input_llama_sampler setter);
    }
