// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.llamacpp;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.llamacpp.global.llamacpp.*;


    @Properties(inherit = us.ihmc.llamacpp.LlamaCPPConfig.class)
public class llama_sampler_seq_config extends Pointer {
        static { Loader.load(); }
        /** Default native constructor. */
        public llama_sampler_seq_config() { super((Pointer)null); allocate(); }
        /** Native array allocator. Access with {@link Pointer#position(long)}. */
        public llama_sampler_seq_config(long size) { super((Pointer)null); allocateArray(size); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public llama_sampler_seq_config(Pointer p) { super(p); }
        private native void allocate();
        private native void allocateArray(long size);
        @Override public llama_sampler_seq_config position(long position) {
            return (llama_sampler_seq_config)super.position(position);
        }
        @Override public llama_sampler_seq_config getPointer(long i) {
            return new llama_sampler_seq_config((Pointer)this).offsetAddress(i);
        }
    
        public native @Cast("llama_seq_id") int seq_id(); public native llama_sampler_seq_config seq_id(int setter);
        public native llama_sampler sampler(); public native llama_sampler_seq_config sampler(llama_sampler setter);
    }
