// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.llamacpp;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.llamacpp.global.llamacpp.*;


    // used in chat template
    @Properties(inherit = us.ihmc.llamacpp.LlamaCPPConfig.class)
public class llama_chat_message extends Pointer {
        static { Loader.load(); }
        /** Default native constructor. */
        public llama_chat_message() { super((Pointer)null); allocate(); }
        /** Native array allocator. Access with {@link Pointer#position(long)}. */
        public llama_chat_message(long size) { super((Pointer)null); allocateArray(size); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public llama_chat_message(Pointer p) { super(p); }
        private native void allocate();
        private native void allocateArray(long size);
        @Override public llama_chat_message position(long position) {
            return (llama_chat_message)super.position(position);
        }
        @Override public llama_chat_message getPointer(long i) {
            return new llama_chat_message((Pointer)this).offsetAddress(i);
        }
    
        public native @Cast("const char*") BytePointer role(); public native llama_chat_message role(BytePointer setter);
        public native @Cast("const char*") BytePointer content(); public native llama_chat_message content(BytePointer setter);
    }
