// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.llamacpp;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.llamacpp.global.llamacpp.*;


    @Properties(inherit = us.ihmc.llamacpp.LlamaCPPConfig.class)
public class llama_sampler_data extends Pointer {
        static { Loader.load(); }
        /** Default native constructor. */
        public llama_sampler_data() { super((Pointer)null); allocate(); }
        /** Native array allocator. Access with {@link Pointer#position(long)}. */
        public llama_sampler_data(long size) { super((Pointer)null); allocateArray(size); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public llama_sampler_data(Pointer p) { super(p); }
        private native void allocate();
        private native void allocateArray(long size);
        @Override public llama_sampler_data position(long position) {
            return (llama_sampler_data)super.position(position);
        }
        @Override public llama_sampler_data getPointer(long i) {
            return new llama_sampler_data((Pointer)this).offsetAddress(i);
        }
    
        public native ggml_tensor logits(); public native llama_sampler_data logits(ggml_tensor setter);
        public native ggml_tensor probs(); public native llama_sampler_data probs(ggml_tensor setter);
        public native ggml_tensor sampled(); public native llama_sampler_data sampled(ggml_tensor setter);
        public native ggml_tensor candidates(); public native llama_sampler_data candidates(ggml_tensor setter);
    }
