// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.llamacpp;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.llamacpp.global.llamacpp.*;


    @Properties(inherit = us.ihmc.llamacpp.LlamaCPPConfig.class)
public class llama_logit_bias extends Pointer {
        static { Loader.load(); }
        /** Default native constructor. */
        public llama_logit_bias() { super((Pointer)null); allocate(); }
        /** Native array allocator. Access with {@link Pointer#position(long)}. */
        public llama_logit_bias(long size) { super((Pointer)null); allocateArray(size); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public llama_logit_bias(Pointer p) { super(p); }
        private native void allocate();
        private native void allocateArray(long size);
        @Override public llama_logit_bias position(long position) {
            return (llama_logit_bias)super.position(position);
        }
        @Override public llama_logit_bias getPointer(long i) {
            return new llama_logit_bias((Pointer)this).offsetAddress(i);
        }
    
        public native @Cast("llama_token") int token(); public native llama_logit_bias token(int setter);
        public native float bias(); public native llama_logit_bias bias(float setter);
    }
