// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.llamacpp;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.llamacpp.global.llamacpp.*;


    @Properties(inherit = us.ihmc.llamacpp.LlamaCPPConfig.class)
public class llama_model_imatrix_data extends Pointer {
        static { Loader.load(); }
        /** Default native constructor. */
        public llama_model_imatrix_data() { super((Pointer)null); allocate(); }
        /** Native array allocator. Access with {@link Pointer#position(long)}. */
        public llama_model_imatrix_data(long size) { super((Pointer)null); allocateArray(size); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public llama_model_imatrix_data(Pointer p) { super(p); }
        private native void allocate();
        private native void allocateArray(long size);
        @Override public llama_model_imatrix_data position(long position) {
            return (llama_model_imatrix_data)super.position(position);
        }
        @Override public llama_model_imatrix_data getPointer(long i) {
            return new llama_model_imatrix_data((Pointer)this).offsetAddress(i);
        }
    
        public native @Cast("const char*") BytePointer name(); public native llama_model_imatrix_data name(BytePointer setter);
        public native @Const FloatPointer data(); public native llama_model_imatrix_data data(FloatPointer setter);
        public native @Cast("size_t") long size(); public native llama_model_imatrix_data size(long setter);
    }
