name: Build llamacpp-javacpp natives

on:
  workflow_dispatch:

permissions:
  contents: write

# For the Linux builds, see https://github.com/ggml-org/llama.cpp/blob/master/docs/build.md

jobs:
  build-linux-cuda-x86_64:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Compile native library (x86_64)
        run: |
          bash cppbuild-docker-linux-cuda-x86_64.bash
      - name: Commit generated java and native libraries
        uses: EndBug/add-and-commit@v9
        with:
          add: '*.java *.so' # Only commit generated java from Linux
          author_name: ihmc-rosie
          author_email: rosie@ihmc.us
          message: 'Rebuild natives for Linux with CUDA (x86_64)'
          push: true
