name: Build llamacpp-javacpp natives

on:
  workflow_dispatch:

permissions:
  contents: write

# For the Linux builds, see https://github.com/ggml-org/llama.cpp/blob/master/docs/build.md

jobs:
  build-linux-cuda-x86_64:
    runs-on: [self-hosted, ihmc-runner-nvidia]
    container:
      image: nvidia/cuda:12.8.0-devel-ubuntu22.04
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install git wget curl cmake build-essential -y
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Compile native library (x86_64)
        run: |
          bash cppbuild.bash
      - name: Commit generated java and native libraries
        uses: EndBug/add-and-commit@v9
        with:
          add: '*.java *.so' # Only commit generated java from Linux
          author_name: ihmc-rosie
          author_email: rosie@ihmc.us
          message: 'Rebuild natives for Linux with CUDA (x86_64)'
          push: true
